import { defaultEmailOptions, transporter } from "../config/mailer.config.js";
import { PASSWORD_RESET_REQUEST_TEMPLATE, PASSWORD_RESET_SUCCESS_TEMPLATE, VERIFICATION_EMAIL_TEMPLATE, WELCOME_EMAIL_TEMPLATE } from "./emailTemplates.js";

// Reusable Email Sender Function
const sendEmail = async (to, subject, htmlContent) =>{
     try {
          const mailOptions = {
               ...defaultEmailOptions,
               to,
               subject,
               html: htmlContent,
          };
          const info = await transporter.sendMail(mailOptions);
          console.log(`Email sent successfully to ${to}: ${info.messageId}`) // unique ID of that specific email // automatically generated by Nodemailer
          return { success: true, messageId: info.messageId };
     } catch (error) {
          console.error(`Failed to send email to ${to}:`, error);
          throw new Error (`Email sending failed: ${error.message}`);
     }
};

// 1> Email Verification with OTP

export const sendVerificationEmail = async (email,verificationCode) => {
     const htmlContent = VERIFICATION_EMAIL_TEMPLATE
          .replace("{verificationCode}", verificationCode);
     return sendEmail(email, 'Verify Email Address', htmlContent);
};

// 2> Email Verification Success
// export const verificationSuccessEmail = async () => {}


// 2> Welcome Email

export const sendWelcomeEmail = async (username, email) => {
     const htmlContent = WELCOME_EMAIL_TEMPLATE
          .replace("{username}", username);
     return sendEmail(email, 'Welcome to Our Platform! &#x1F973;', htmlContent);
};

// 3> Password Reset Request

export const sendPasswordResetEmail = async (email, resetURL) => {
     const htmlContent = PASSWORD_RESET_REQUEST_TEMPLATE
          .replace(/{resetURL}/g, resetURL);
     return sendEmail(email, "Password Reset Request 🔑", htmlContent);
};

// 4> Password Reset Success

export const sendResetSuccessEmail = async (email, username) => {
     const htmlContent = PASSWORD_RESET_SUCCESS_TEMPLATE
          .replace('{username}', username);
     return sendEmail(email, "Password Reset Successful 🎉", htmlContent);
}

//Password Change Confirmation With IP

//Account Deletion Confirmation

//Notification Email

//Batch email sender -for newsletters, announcements